### ISSUE TITLE
package 1.1.0 is missing on pypi

### ISSUE THREAD

**Issue by woutervh** [vladimarius/imapy#9]
Please upload the package of the new release 1.1.0 to pypi, 
so it can be pip-installed.

many thanks.

**Comment by vladimarius** [comment]
That's weird. I see it on pypi but cannot install new version.
Looking into it.

**Comment by vladimarius** [comment]
installing it with:
pip install -v -v -v imapy

# returns the following output:

Downloading/unpacking imapy
  Getting page https://pypi.python.org/simple/imapy/
  URLs to search for versions for imapy:
- https://pypi.python.org/simple/imapy/
  Analyzing links from page https://pypi.python.org/simple/imapy/
    Found link https://pypi.python.org/packages/source/i/imapy/imapy-1.0.0.tar.gz#md5=35dd972b0eabd1c8d9d451748d43c12a (from https://pypi.python.org/simple/imapy/), version: 1.0.0
    Found link https://pypi.python.org/packages/source/i/imapy/imapy-1.0.1.tar.gz#md5=ea85d823b6073a6a8bf00fad7455d049 (from https://pypi.python.org/simple/imapy/), version: 1.0.1
    Found link https://pypi.python.org/packages/source/i/imapy/imapy-1.0.2.tar.gz#md5=914f1b7dd9e7f29a38e55a7fc44ab832 (from https://pypi.python.org/simple/imapy/), version: 1.0.2
    Found link https://pypi.python.org/packages/source/i/imapy/imapy-1.0.3.tar.gz#md5=2d5da8e3c49eabe413c4b5f437187226 (from https://pypi.python.org/simple/imapy/), version: 1.0.3
  Using version 1.0.3 (newest of versions: 1.0.3, 1.0.2, 1.0.1, 1.0.0)
  Downloading imapy-1.0.3.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/i/imapy/imapy-1.0.3.tar.gz#md5=2d5da8e3c49eabe413c4b5f437187226 (from https://pypi.python.org/simple/imapy/)
  =====================

Although i can clearly see 1.1.0 here:
https://pypi.python.org/pypi/imapy

So for some reason pypi doesn't show all available packages.
Seems like the root of the problem is some pypi-related caching issues.

**Comment by vladimarius** [comment]
Please check it.
Should be there now.

**Comment by woutervh** [comment]
yes, I see the downloadable package now.
